config/routes.rb
Rails.application.routes.draw do
  resources :categories
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :admins
  devise_for :users

  devise_scope :user do
      get '/users/sign_out' => 'devise/sessions#destroy'
  end

  # resources :posts
  resources :subscribers

  resources :posts do
    resources :tasties
    resources :yummies
    resources :favorites
  end

  get 'posts/index'

  get 'about', to: 'about#index'
  get 'welcome', to: 'welcome#index'
  get 'all_collections', to: 'all_collections#index'
  get 'landing/index', to: 'landing#index'
  get 'partners/index', to: 'partners#index'
  get 'styleguide', to: 'styleguide#index'
  get 'main', to: 'main#index'
  root 'landing#index'

  get 'users', to: 'users#index'
  get 'users/:id' => 'users#show', :as => :user
  delete 'users/:id', to: 'users#destroy'

  get 'admins', to: 'admins#index'
  get 'admins/:id' => 'admins#show', :as => :admin
  delete 'admins/:id', to: 'admins#destroy'

  get 'author', to: 'author#index'
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/like_def.rb
class LikeDef < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
		validates :name, :presence => true
		validates :title, :presence => true,
											:length => { :minimum => 5 }

mount_uploader :image, ImageUploader
has_many :tasties, dependent: :destroy
has_many :yummies, dependent: :destroy
has_many :favorites, dependent: :destroy

belongs_to :user
belongs_to :category


end

app/models/subscriber.rb
class Subscriber < ApplicationRecord
  validates :email, presence: true
end

app/models/tasty.rb
class Tasty < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
   # has_many :likesdef, dependent: :destroy
   has_many :yummies, dependent: :destroy
   has_many :tasties, dependent: :destroy
   has_many :favorites, dependent: :destroy
   has_many :favorited_posts, :through => :favorites, :source => :post
end

app/models/yummy.rb
class Yummy < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # http_basic_authenticate_with :name => "admin", :password => "admin", :except => [:show, :index]
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /posts
  # GET /posts.json
  def index
    if params.has_key?(:category)
      @category = Category.find_by_name(params[:category])
      @posts = Post.where(category: @category)
    else
      @posts = Post.all
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params.merge(user_id: current_user.id))

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Пост создан' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Пост обновлен' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Пост удален' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:name, :title, :content, :image, :time, :ingredients, :category_id)
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/likesdef_helper.rb
module LikesdefHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/partners_helper.rb
module PartnersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tasties_helper.rb
module TastiesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/yummies_helper.rb
module YummiesHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  
  <div class="field">
    <%= form.label :category_id %>
    <%= form.select :category_id, Category.pluck(:name, :id) %>
  </div>

  <div>
	<%= form.label :image %>
	<%= form.file_field :image %>
  </div>

  <div class="field">
    <%= form.label :time %>
    <%= form.text_field :time %>
  </div>

  <div class="field">
	<%= form.label :ingredients %>
	<%= form.text_area :ingredients %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.cktext_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>

<% end %>

app/views/posts/edit.html.erb
<h1>Редактировать пост</h1>

<%= render 'form', post: @post %>

<%= link_to 'Посмотреть', @post %> |
<%= link_to 'Вернуться назад', posts_path %>

app/views/posts/index.html.erb
<%= link_to 'Новый пост', new_post_path, class: 'btn_new-post' %>
 <!-- link_to 'Новая категория', new_category_path, class: 'btn_new-cat' %> %> -->
<h1 class="test">Рецепты</h1>
<!-- <.h2>Все катагории</h2> -->
  <!-- Category.all.each do |cat|  %> -->
  <!-- link_to cat.name, posts_path(category: cat.name) %> <br> %> end %> %> -->
<table class="posts__main">
  <thead>
    <tr>
      <th></th>
      <th>Название</th>
      <th>Категория</th>
      <th>Автор</th>
      <th>Действие</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= image_tag(post.image.url, alt: 'Image') if post.image? %> </td>
        <td><%= post.title %></td>
        <td><%= post.category.name %></td>
        <td><%= post.name %></td>
        <td><%= link_to 'Посмотреть', post %> <br>
        <%= link_to 'Редактировать', edit_post_path(post) %><br>
        <%= link_to 'Удалить', post, method: :delete, data: { confirm: 'Вы уверены?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/posts/new.html.erb
<h1>Новый пост</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<div>
<%= link_to '<- Вернуться назад', posts_path, class: 'show__post__btn__back' %>
<% if user_signed_in? %>
  <%= link_to 'Редактировать', edit_post_path(@post) , class: 'edit__post__btn__back' %>
<% end %>
</div>

<p class="show__name">
  <strong class="show__name__pre">Автор:</strong>
  <%= @post.name %>
</p>

<p class="show__title">
  <strong class="show__title__pre">Название:</strong>
  <%= @post.title %>
</p>

<p class="show__category">
  <strong>Категория:</strong>
  <%= @post.category.name %>
</p>

<%= image_tag(@post.image.url, class: 'show__img', alt: 'Image') if @post.image? %>

<p class="show__time">
	<strong class="show__time__pre">Время приготовления:</strong>
	<%= @post.time %>
</p>

<p class="show__ingredients">
  <strong class="show__ingredients_pre">Ингредиенты:</strong>
  <%= @post.ingredients %>
</p>

<p class="show__content">
  <strong class="show__content__pre">Текст рецепта:</strong>
  <%= @post.content.html_safe %>
</p>

<p><% if user_signed_in? %>
  <%= button_to 'Add to Favorite', post_favorites_path(@post), method: :post %>
  <% else %>
  <%= button_to 'Add to Favorite', new_user_session_path %>
<% end %>
</p>


<div class="show__like__count">
  <div class="show__like__count__tasty">
    <p>
      <%= @post.tasties.count %> <%= (@post.tasties.count) == 1 ? 'Tasty' : 'Tasties'%>
    </p>

    <% if user_signed_in? %>

      <% pre_tasty = @post.tasties.find { |tasty| tasty.user_id == current_user.id} %>
      <% if pre_tasty %>
        <%= button_to 'Untasty', post_tasty_path(@post, pre_tasty), method: :delete, class: 'show__like__count__btn' %>
      <% else %>
        <%= button_to 'Tasty', post_tasties_path(@post), method: :post %>
      <% end %>
    <% end %>
  </div>

  <div class="show__like__count__yummy">
    <p>
      <%= @post.yummies.count %> <%= (@post.yummies.count) == 1 ? 'Yummy' : 'Yummies'%>
    </p>
    <% if user_signed_in? %>
      <% pre_yummy = @post.yummies.find { |yummy| yummy.user_id == current_user.id} %>
      <% if pre_yummy %>
        <%= button_to 'Unyummy', post_yummy_path(@post, pre_yummy), method: :delete, class: 'show__like__count__yummy__btn'  %>
      <% else %>
        <%= button_to 'Yummy', post_yummies_path(@post), method: :post, class: 'show__like__count__yummy__btn'   %>
      <% end %>
    <% end %>
  </div>
</div>