config/routes.rb
Rails.application.routes.draw do
  resources :categories
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :admins
  devise_for :users

  devise_scope :user do
      get '/users/sign_out' => 'devise/sessions#destroy'
  end

  # resources :posts
  resources :subscribers

  resources :posts do
    resources :tasties
    resources :yummies
    resources :favorites
  end

  get 'posts/index'

  get 'about', to: 'about#index'
  get 'welcome', to: 'welcome#index'
  get 'all_collections', to: 'all_collections#index'
  get 'landing/index', to: 'landing#index'
  get 'partners/index', to: 'partners#index'
  get 'styleguide', to: 'styleguide#index'
  get 'main', to: 'main#index'
  root 'landing#index'

  get 'users', to: 'users#index'
  get 'users/:id' => 'users#show', :as => :user
  delete 'users/:id', to: 'users#destroy'

  get 'admins', to: 'admins#index'
  get 'admins/:id' => 'admins#show', :as => :admin
  delete 'admins/:id', to: 'admins#destroy'

  get 'author', to: 'author#index'
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/like_def.rb
class LikeDef < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
		validates :name, :presence => true
		validates :title, :presence => true,
											:length => { :minimum => 5 }

mount_uploader :image, ImageUploader
has_many :tasties, dependent: :destroy
has_many :yummies, dependent: :destroy
has_many :favorites, dependent: :destroy

belongs_to :user
belongs_to :category


end

app/models/subscriber.rb
class Subscriber < ApplicationRecord
  validates :email, presence: true
end

app/models/tasty.rb
class Tasty < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
   # has_many :likesdef, dependent: :destroy
   has_many :yummies, dependent: :destroy
   has_many :tasties, dependent: :destroy
   has_many :favorites, dependent: :destroy
   has_many :favorited_posts, :through => :favorites, :source => :post
end

app/models/yummy.rb
class Yummy < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/likesdef_helper.rb
module LikesdefHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/partners_helper.rb
module PartnersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tasties_helper.rb
module TastiesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/yummies_helper.rb
module YummiesHelper
end

app/views/about/index.html.erb
<section class="section__one">
  <header>
    <h1>
      Refood&nbsp;&mdash; это умная
      <span>
        <%= image_tag 'blue-book', class: 'header__img'%>
        кулинарная книга
      </span>
      , подстраивающая ингредиенты под ваши требования выбора блюд. Это могут быть как идеологические, физиологические или этические
      <span>
        <%= image_tag 'cross-mark', class: 'header__img'%>
         ограничения
      </span>
      , <br>так и&nbsp;<span>
        <%= image_tag 'face-with-cold-sweat', class: 'header__img'%>
        отсутствие
      </span>
        необходимых продуктов в&nbsp;холодильнике. Сервис поможет вам избавиться от&nbsp;насущных проблем, с&nbsp;которыми вы&nbsp;регулярно сталкиваетесь при подборе рецепты и&nbsp;на&nbsp;этапе приготовления. Теперь вы&nbsp;сможете полностью отдаться процессу
      <span>
        <%= image_tag 'fork-and-knife', class: 'header__img'%>
         готовки </span>, а&nbsp;мы
      <span>
        <%= image_tag 'clock', class: 'header__img'%>
         сэкономим
      </span>
       ваше время и&nbsp;позаботимся обо всем остальном!
    </h1>
  </header>

  <div class="main">
    <h4>
      Целевая аудитория
    </h4>

    <div class="main__card">
      <div class="main__card__one">
        <h5>Основная</h5>
        <p>Люди, имеющие этические, физиологические или религиозные требования к&nbsp;еде</p>
      </div>
      <div class="main__card__two">
        <h5>Косвенная</h5>
        <p>Люди, которые готовят дома</p>
      </div>
    </div>

  </div>
</section>

<section class="section__two">
  <div class="main__two">
    <h4>Выбранные для реализации фичи</h4>
    <div class="main__two__p">
      <p>Лайк, апвойт/даунвойт, стар, рэйт, сэйв, клэп, репост</p>
      <p>Коллекции (сохранить в коллекцию/доску/плейлист/фотогалерею)</p>
      <p>Поиск, саджест в поиске, поисковая выдача</p>
      <p>Система сортировки/фильтров поисковой выдачи</p>
      <p>Категории и/или теги (одна или много)</p>
      <p>Посты (текст, фото, видео, гибрид)</p>
    </div>
  </div>
  <div class="main__three">
    <h4>Выводы по CusDev</h4>
    <p>По&nbsp;результатам исследования в&nbsp;замене ингредиентов нуждаются не&nbsp;только люди, имеющие этические, физиологические и&nbsp;идиологические требования, но&nbsp;и&nbsp;потребители без ограничений в&nbsp;питании</p>
    <div class="main__three__card_one">
      <span>
        <%= image_tag 'peanut', class: 'img__main__three__card'%>
        орехи
      </span>

      <span>
        <%= image_tag 'pineapple', class: 'img__main__three__card'%>
        ананас
      </span>

      <span>
        <%= image_tag 'cut-of-meat', class: 'img__main__three__card'%>
        мясо
      </span>

      <span>
        <%= image_tag 'onion', class: 'img__main__three__card'%>
        лук
      </span>

      <span>
        <%= image_tag 'pepper', class: 'img__main__three__card'%>
        болгарский перец
      </span>
    </div>

    <div class="main__three__card_two">
      <span>
        <%= image_tag 'tomato', class: 'img__main__three__card'%>
        помидор
      </span>

      <span>
        <%= image_tag 'mango', class: 'img__main__three__card'%>
        манго
      </span>

      <span>
        <%= image_tag 'glass-of-milk', class: 'img__main__three__card'%>
        молоко
      </span>

      <span>
        <%= image_tag 'mushroom', class: 'img__main__three__card'%>
        грибы
      </span>
    </div>
  </div>
</section>

<section class="section__three">

  <div class="main__four">
    <h4>Индивидуальные предпочтения</h4>
    <p>При регистрации вы&nbsp;указываете ограничения в&nbsp;еде, и&nbsp;рецепты подбираются исходя из&nbsp;вашего рациона питания</p>
    <%= image_tag 'phone', class: 'img__phone'%>
  </div>

  <div class="main__five">
    <h4>Замена ингредиентов</h4>

    <!-- yellow card -->
    <div class="main-five-card">
      <nav>
      </nav>

    <div class="main_five_card">
      <%= image_tag 'plate-salad', class: 'main_five_card__img'%>

      <div class="main__five__ingredients">
        <!-- first line -->
        <p>
        <span>
          <%= image_tag 'cut-of-meat', class: 'main__five__ingredients__img'%>
          говядина
        </span>
        300 г.
        </p>

        <!-- second line -->
        <p>
        <span>
          <%= image_tag 'sake', class: 'main__five__ingredients__img'%>
          соевый соус
        </span>
        6 ст. л.
        </p>

        <!-- thirst line -->
        <p>
        <span>
          <%= image_tag 'onion', class: 'main__five__ingredients__img'%>
          лук репчатый
        </span>
        1 шт.
        </p>

        <!-- four line -->
        <p>
        <span>
          <%= image_tag 'mushroom', class: 'main__five__ingredients__img'%>
          шампиньоны
        </span>
        200 г.
        </p>

        <!-- five line -->
        <p>
        <span>
          <%= image_tag 'pepper', class: 'main__five__ingredients__img'%>
          болгарский перец
        </span>
        1 шт.
        </p>

        <!-- six line -->
        <p>
        <span>
          <%= image_tag 'leafy', class: 'main__five__ingredients__img'%>
          листья салата
        </span>
        200 г.
        </p>

        <!-- six line -->
        <p>
        <span>
          <%= image_tag 'chestnut', class: 'main__five__ingredients__img'%>
          орех
        </span>
        50 г.
        </p>
      </div>
    </div>
  </div>

    <!-- all groups of text -->
    <div class="main__five__group">

      <!-- one mini-group of text -->
      <div class="main__five__group__p">
        <h4>Животного происхождения</h4>
        <p>
          <span>
            <%= image_tag 'cut-of-meat', class: 'main__five__group__p__img'%>
            говядина
          </span>
          <%= image_tag 'arrow', class: 'main__five__group__p__img__arrow'%>
          <span>
            <%= image_tag 'peanut', class: 'main__five__group__p__img'%>
            фасоль
          </span>
        </p>
      </div>

      <!-- one mini-group of text -->
      <div class="main__five__group__p">
        <h4>Пищевые аллергены</h4>
        <p>
          <span>
            <%= image_tag 'chestnut', class: 'main__five__group__p__img'%>
            орех
          </span>
          <%= image_tag 'arrow', class: 'main__five__group__p__img__arrow'%>
          <span>
            <%= image_tag 'pumpkin', class: 'main__five__group__p__img'%>
            тыквенные семечки
          </span>
        </p>
      </div>

      <!-- one mini-group of text -->
      <div class="main__five__group__p">
        <h4>Отсутствие ингредиентов дома</h4>
        <p>
          <span>
            <%= image_tag 'pepper', class: 'main__five__group__p__img'%>
            болгарский перец
          </span>
          <%= image_tag 'arrow', class: 'main__five__group__p__img__arrow'%>
          <span>
            <%= image_tag 'tomato', class: 'main__five__group__p__img'%>
            помидор
          </span>
        </p>
      </div>
    </div>
  </div>
</section>

<section class="section__four">
  <div class="main__seven">
    <h4>Индивидуальные подборки рецептов</h4>
    <p>Сервис решает проблему поиска рецепта из&nbsp;разных источников, подстраивая ингредиенты под вас</p>
    <%= image_tag 'phone-2', class: 'main__six__img'%>
  </div>

  <footer>
    <h3>
      Узнайте о запуске
      <span>
        <%= image_tag 'mobile-phone', class: 'emj__phone'%></span>
        сервиса,
        <br>
        подпишитесь
        <span>
          <%= image_tag 'postbox', class: 'emj__postbox'%></span>
          на рассылку
        </h3>

        <%= render "subscribers/form" %>
        <div class="btn__footer">
          <%= link_to "Сплэш", welcome_path %>
          <%= link_to "Посты", posts_path %>
        </div>
      </footer>

</section>

















<!-- // -->